---
# Site settings
site_name: EuroSciPy Conference
site_url: https://pioneershub.github.io/euroscipy-conference/
site_author: [
  "Alexander Hendorf",
]
site_description: >-
  Template for organizing a volunteer-driven conference.

# Repository at GitHub
repo_name: PioneersHub/euroscipy-conference
repo_url: https://github.com/PioneersHub/euroscipy-conference

# Copyright for footer
copyright:
  start_year: 2024
  owner: Pioneers Hub gGmbH

# Event details
event:
  event_name: "EuoSciPy 2025"
  start_date: "August 2025 TBA"
  end_date: "five days later"
  day_before: "August 2025 TBA"
  month: "August"
  year: "2025"
  location: "Somewhere, Poland"
  # The URL for the Call for Committee application form
  contact_email: "info@euroscipy.org"
  # program
  cfp_open: "03.03.2025"
  cfp_close: "28.04.2025"
  review_deadline: "10.06.2025"
  cfp_speakers_notifications: "10.06.2025"
  cfp_link: "/to-be-announced/"
  voting_url: "/to-be-announced/"
  voting_start: "to-be-announced"
  voting_end: "to-be-announced"
  contact_program: "/to-be-announced/"
  # diversity
  financial_aid_open: "03.03.2025"
  financial_aid_close: "28.04.2025"
  financial_aid_notifications: "15.05.2025"
   # committees
  call_for_committee_open: "14.01.2025"
  call_for_committee_close: "31.01.2025"
  apply_url_committees: "https://forms.gle/SeSrnv1UKbxDNu9e9"
  # volunteers
  call_for_volunteers_open: "to-be-announced"
  call_for_volunteers_close: "to-be-announced"
  apply_url_volunteers: "/to-be-announced/"
  # tickets
  ticket_sales_open: "01.01.2025"
  ticket_sales_late_bird: "01.03.2025"

  # Code of Conduct Team
  coc_email: coc-reports@euroscoipy.org
  team_members: |
    - to-be-announced
    - to-be-announced
    - to-be-announced
    - to-be-announced
  backup_team_members: |
    - to-be-announced email@domain.com
    - to-be-announced email@domain.com

committees:
  # Committee names must match the headers in the committees.md file
  # Expected workloads and milestones for each committee
  "coc":
    requirements:
      attend_conference: true
    workload:
      average: "1 hour per week"
      start: "03.03.2025"
      peak: "During the conference"
      end: "Until all reports have been resolved"
  "communication":
    attend_conference: true
    workload:
      average: "1-2 hours per week"
      start: "15.02.2025"
      peak: "March/April and August 2025"
      end: "four weeks after conference"
  "diversity":
    attend_conference: true
    workload:
      average: "1-2 hours per week"
      start: "15.02.2025"
      peak: "May 2025"
      end: "two weeks after conference"
  "experience":
    attend_conference: true
    workload:
      average: "1-2 hours per week"
      start: "start-date-here"
      peak: "peak-dates-here"
      end: "end-date-here"
  "infrastructure":
    attend_conference: true
    workload:
      average: "1-2 hours per week"
      start: "start-date-here"
      peak: "peak-dates-here"
      end: "end-date-here"
  "on_site_operations":
    attend_conference: true
    workload:
      average: "1-2 hours per week"
      start: "Three months before conference, 1-2 hours a week"
      peak: "Four weeks before the conference 4-5 hours per week. During conference - all day"
      end: "End of the conference"
  "program":
    attend_conference: false
    workload:
      average: "1-2 hours per week"
      start: "15.05.2025, 1-2 hours a week"
      peak: "May 4-5 hours per week for 3 weeks."
      end: "End of the conference"
  "steering":
    attend_conference: true
    workload:
      average: "1-2 hours per week"
      start: "6 months before the conference, 1-2 hours per week"
      peak: "Onboarding for new committees and major decision process times, 3-4 hours a week"
      end: "End of the conference"
  "swag":
    attend_conference: true
    workload:
      average: "1-2 hours per week"
      start: "1 month before the ticket sales"
      peak: "4 weeks before the conference, collecting final numbers for order"
      end: "Conference day"
  "video":
    attend_conference: true
    workload:
      average: "1-2 hours per week"
      start: "Three months before conference"
      peak: "During the conference"
      end: "Until all videos have been released"

# custom config for social cards customization
social_cards:
  dirs:
    # relative paths from the repository root
    cache_dir: "./.cache/plugin/social"
    site_dir: "./site/assets/images/social"
    # convention, rename your logo accordingly
  logo_path: "./docs/assets/images/social_card_logo.png"
